name: gcp-storage-sync

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: weslenng/gcp-storage-sync@master
        with:
          args: -d
        env:
          GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SA_KEY }}
          GCP_STORAGE_BUCKET: ${{ secrets.GCP_PROJECT_ID }}
          SOURCE_DIR: "mentoring/build/libs/study-0.0.1-SNAPSHOT.jar"
          DEST_DIR: "~/"
          
